### ISSUE TITLE
Streaming behavior

### ISSUE THREAD

**Issue by TheoLvs** [Azure-Samples/function-python-ai-langchain#1]
Hello ! 

Thanks for this great code sample, do you know if it's compatible with streaming configuration in Langchain ? (display letter by letter)
And if not how would you do that ? 

Thanks a lot, 
Theo

**Comment by paulyuk** [comment]
Hi Theo!  Great question and short answer, no not currently.  But it could be changed easily in the function_app.py -- this approach with functions lets you use any langchain sdk patterns you want.

Have you looked at this?
https://dev.to/fibonacid/quick-guide-for-langchain-streaming-via-expressjs-iod

**Comment by paulyuk** [comment]
Closing but let me know if this is an issue
