### ISSUE TITLE
File name spelling error

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/function-python-ai-langchain#2]
**Describe the issue:**
`requirements.text` should be updated to `requirements.txt`. 
related link: 

- https://github.com/Azure-Samples/function-python-ai-langchain#using-functions-cli
- https://github.com/Azure-Samples/function-python-ai-openai-chatgpt#using-functions-cli

![image](https://github.com/Azure-Samples/function-python-ai-langchain/assets/80496810/986b0e52-9428-4bea-8a04-e334c2dea688)

@hemarina for notification.

**Comment by paulyuk** [comment]
Fixed by #4
