### ISSUE TITLE
Run `azd up ` fail

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/function-python-ai-langchain#3]
**Describe the issue:**
When executing `azd up` according to [README.md](https://github.com/Azure-Samples/function-python-ai-langchain/blob/main/README.md), the error is as follows:
![image](https://github.com/Azure-Samples/function-python-ai-langchain/assets/80496810/00ec1656-8e70-42a6-8878-2cf7dedff1d6)

**Repro Steps:**
1. Clone the code to local.
2.  Run `azd up`.

**Environment:**
- OS: Windows desktop.

**Expected behavior:**
 Run `azd up` can pass.

@hemarina for notification.

**Comment by paulyuk** [comment]
Thank you for the report.
This needs to sync with this change:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/322

**Comment by v-jiaodi** [comment]
@paulyuk Retest when I synchronize this change https://github.com/Azure-Samples/azure-search-openai-demo/pull/322. At first, I got the following error：
![image](https://github.com/Azure-Samples/function-python-ai-langchain/assets/80496810/6a470de8-65a3-4be9-b8cb-83c3b9106b72)
But when I execute `azd up` again, it works fine.
![image](https://github.com/Azure-Samples/function-python-ai-langchain/assets/80496810/acb523b5-97c7-4f50-9f4a-6264b8688203)

**Comment by paulyuk** [comment]
Wow, thank you for trying after a sync.

There is one special workaround I notice they did in main.bicep which makes that error go away:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/21bac5de946669390014b278c5cf3208a06f1a16/infra/main.bicep#L61C39-L61C39

Essentially, they made another reference to the resource group, and created an implicit Dependson relationship from that resource group.  With depends on in place, the RG will always get created before the AI resource.  For some reason, today, in ARM/bicep there is a timing issue!

My PR will have the full fix.  it's coming momentarily.

**Comment by paulyuk** [comment]
Beware to anyone testing this issue and hitting the quota issues, you will likely need to purge your deleted resources first to free up capacity before retrying.
https://learn.microsoft.com/en-us/azure/cognitive-services/manage-resources?tabs=azure-portal#purge-a-deleted-resource

**Comment by paulyuk** [comment]
Fixed by #4

**Comment by v-jiaodi** [comment]
@paulyuk Retest with the latest code, still encounter this error: https://github.com/Azure-Samples/function-python-ai-langchain/issues/3#issuecomment-1622893551
